# Generated by Django 2.1.4 on 2019-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=256)),
                ('Event_Date', models.DateField()),
                ('Event_Time', models.TimeField()),
                ('Event_Description', models.CharField(max_length=256)),
            ],
        ),
    ]
