# Generated by Django 2.1.4 on 2019-03-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventForm',
            new_name='Event',
        ),
    ]
